# web_app/routes/vis_routes.py

from flask import Blueprint, render_template

vis_routes = Blueprint("vis_routes", __name__)

import os
import sqlite3
import pandas as pd
import numpy as np
import json

DEV_DB_FILEPATH = os.path.join(os.path.dirname(__file__), "..", "sis_vis_dev.db")

@vis_routes.route("/visuals")
def visuals():
    #FilePath
    dev_conn = sqlite3.connect(DEV_DB_FILEPATH)
    print("Connection:", dev_conn)
    cursor1 = dev_conn.cursor()
    print("CURSOR:", cursor1)
    # gradebook_query = "SELECT t.student_name, s.assignment_name, s.score, c.course_name, r.teacher_name FROM student t LEFT JOIN scores s ON t.id = s.student_id LEFT JOIN courses c ON s.class_id = c.id LEFT JOIN teachers r ON c.teacher_id = r.id;"
    cursor1.close()
    colz = ['Student', 'Assignment', 'Score', 'Class', 'Teacher']
    gradebook_df = pd.DataFrame(gradebook_result, columns=colz)
    grade_data =[{'assignment_name': 'hw_1',
    'course_name': "Gary's Dart Class",
    'score': 81,
    'student_name': 'Tony',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_2',
    'course_name': "Gary's Dart Class",
    'score': 88,
    'student_name': 'Tony',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_3',
    'course_name': "Gary's Dart Class",
    'score': 82,
    'student_name': 'Tony',
    'teacher_name': 'Gary'},
    {'assignment_name': 'exam_1',
    'course_name': "Gary's Dart Class",
    'score': 91,
    'student_name': 'Tony',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_1',
    'course_name': "Gary's Dart Class",
    'score': 77,
    'student_name': 'Sandy',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_2',
    'course_name': "Gary's Dart Class",
    'score': 98,
    'student_name': 'Sandy',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_3',
    'course_name': "Gary's Dart Class",
    'score': 81,
    'student_name': 'Sandy',
    'teacher_name': 'Gary'},
    {'assignment_name': 'exam_1',
    'course_name': "Gary's Dart Class",
    'score': 54,
    'student_name': 'Sandy',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_1',
    'course_name': "Gary's Dart Class",
    'score': 99,
    'student_name': 'Ryan',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_2',
    'course_name': "Gary's Dart Class",
    'score': 98,
    'student_name': 'Ryan',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_3',
    'course_name': "Gary's Dart Class",
    'score': 80,
    'student_name': 'Ryan',
    'teacher_name': 'Gary'},
    {'assignment_name': 'exam_1',
    'course_name': "Gary's Dart Class",
    'score': 50,
    'student_name': 'Ryan',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_1',
    'course_name': "Gary's Dart Class",
    'score': 44,
    'student_name': 'Mike',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_2',
    'course_name': "Gary's Dart Class",
    'score': 76,
    'student_name': 'Mike',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_3',
    'course_name': "Gary's Dart Class",
    'score': 95,
    'student_name': 'Mike',
    'teacher_name': 'Gary'},
    {'assignment_name': 'exam_1',
    'course_name': "Gary's Dart Class",
    'score': 90,
    'student_name': 'Mike',
    'teacher_name': 'Gary'},
    {'assignment_name': 'hw_1',
    'course_name': "Jayce's Poetry Class",
    'score': 55,
    'student_name': 'Hugo',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_2',
    'course_name': "Jayce's Poetry Class",
    'score': 66,
    'student_name': 'Hugo',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_3',
    'course_name': "Jayce's Poetry Class",
    'score': 77,
    'student_name': 'Hugo',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'exam_1',
    'course_name': "Jayce's Poetry Class",
    'score': 88,
    'student_name': 'Hugo',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_1',
    'course_name': "Jayce's Poetry Class",
    'score': 85,
    'student_name': 'Jesse',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_2',
    'course_name': "Jayce's Poetry Class",
    'score': 65,
    'student_name': 'Jesse',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_3',
    'course_name': "Jayce's Poetry Class",
    'score': 76,
    'student_name': 'Jesse',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'exam_1',
    'course_name': "Jayce's Poetry Class",
    'score': 50,
    'student_name': 'Jesse',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_1',
    'course_name': "Jayce's Poetry Class",
    'score': 65,
    'student_name': 'Paul',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_2',
    'course_name': "Jayce's Poetry Class",
    'score': 75,
    'student_name': 'Paul',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_3',
    'course_name': "Jayce's Poetry Class",
    'score': 80,
    'student_name': 'Paul',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'exam_1',
    'course_name': "Jayce's Poetry Class",
    'score': 60,
    'student_name': 'Paul',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_1',
    'course_name': "Jayce's Poetry Class",
    'score': 25,
    'student_name': 'Kathi',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_2',
    'course_name': "Jayce's Poetry Class",
    'score': 55,
    'student_name': 'Kathi',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'hw_3',
    'course_name': "Jayce's Poetry Class",
    'score': 40,
    'student_name': 'Kathi',
    'teacher_name': 'Jayce'},
    {'assignment_name': 'exam_1',
    'course_name': "Jayce's Poetry Class",
    'score': 55,
    'student_name': 'Kathi',
    'teacher_name': 'Jayce'}]
    plt.style.use('fast') 
    df = pd.DataFrame.from_dict(grade_data)
    return render_template("index.html")
    # return render_template("visuals.html", df = df)
